### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by trinitroglycerin** [substack/seaport#72]
Is this project still maintained? it works excellently currently but numerous issues/pull requests have no response to them and I don't want to base a foundation for a project on a module that hasn't been updated in a year

**Comment by ilsken** [comment]
Would like to know this too. Shame if it isn't, I remember when being very excited about this project when it was published

**Comment by onbjerg** [comment]
ping @substack

**Comment by vekexasia** [comment]
me too :) Are there any valid alternatives?

**Comment by miketheprogrammer** [comment]
Please do not use this module. Seaport is not stable in production environments.
Please use Thalassa if you really want a node based registry, or use Consul

**Comment by roccomuso** [comment]
+1
